services:
  postgres:
    image: "postgres:latest"
    environment:
      - 'POSTGRES_DB=lab3_kotlin'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=chelovek'
    ports:
      - '6000:5432'
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U chelovek -d lab3_kotlin" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api-lab3:
    build: .
    container_name: 'api-lab3'
    ports:
      - '8090:8080'
    environment:
      - 'DB_USER=chelovek'
      - 'DB_PASSWORD=1234'
      - 'DB_NAME=lab3_kotlin'
      - 'DB_HOST=postgres'
      - 'DB_PORT=5432'
    depends_on:
      - postgres
    networks:
      - app_network
networks:
  app_network:
