spring:
  application:
    name: Lab3KotlinApiDB
  datasource:
    username: ${DB_USER:chelovek}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lab3_kotlin}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        show_sql: true
